### ISSUE TITLE
ci: run c++ tests in an integration build

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#1637]
### Description of new feature

There are four c++ tests in `tests-cpp` that are built, but not run. They require C++17.
```[tasklist]
### Tasks
- [ ] https://github.com/scikit-hep/awkward/pull/2978
- [ ] https://github.com/scikit-hep/awkward/pull/2976
- [ ] https://github.com/scikit-hep/awkward/pull/2977
```

**Comment by jpivarski** [comment]
Is this still true? It's an old issue, and the testing situation may have changed.

If the issue is no longer relevant, please close the issue. Thanks!

**Comment by ianna** [comment]
> Is this still true? It's an old issue, and the testing situation may have changed.
> 
> If the issue is no longer relevant, please close the issue. Thanks!

I think, the issue is still relevant. Only 3 out of four tests are run: 

```
Run import os
  import os
  import pathlib
  import subprocess
  for path in pathlib.Path("build/tests/bin").glob("test_*"):
      if path.is_file():
          print(f"Running {path.name}", flush=True)
          print("::group::Test output", flush=True)
          subprocess.run([path], check=True)
          print("::endgroup::", flush=True)
  shell: /usr/bin/python3 {0}
Running test_1560-builder-options
Test output
Running test_1542-growable-buffer
Test output
Running test_1494-layout-builder
Test output
```

I understand, that the array builder test is not a header-only test - it needs to be linked to `libawkward.so`. Also, we need to check that the dependencies are propagated. For example, changes to the header-only should trigger rebuilding and testing of the array builder:

https://github.com/scikit-hep/awkward/blob/f9a29effed4998054235649c4ee1dfadc059ede0/awkward-cpp/include/awkward/builder/ArrayBuilder.h#L12

Tested in https://github.com/scikit-hep/awkward/pull/2976, https://github.com/scikit-hep/awkward/pull/2977, and https://github.com/scikit-hep/awkward/pull/2978

**Comment by jpivarski** [comment]
I don't think we need a C++ test for ArrayBuilder; it's tested well enough in both Python and Numba. We could just delete that one: [header-only/tests/test_1542-array-builder.cpp](https://github.com/scikit-hep/awkward/blob/main/header-only/tests/test_1542-array-builder.cpp). I just took a look at it, and it doesn't do very much, anyway.

Then we're testing everything (3 out of a total of 3), right? If so, this issue could be considered resolved once test_1542-array-builder.cpp is deleted.
