### ISSUE TITLE
2.1.0 Release Checklist

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2143]
Order of operations:

- [x] Last awkward-cpp release for awkward 2.0.x
- [x] Finish #2276, #2269, #2260, #2280
- [x] Last awkward 2.0.x patch release
- [x] Bump NumPy minimum version to 1.17 in both awkward and awkward-cpp # https://github.com/scikit-hep/awkward/pull/2282
- [x] Release 2.1.0
